import '../domain/driver_flow_models.dart';

/// Driver-app repository contract.
///
/// PRD references:
///  - §11 booking state machine — accept / arrive / start / end / cancel must
///    be distinct API calls (no bundling).
///  - §12 dispatch — explicit decline with `reason_code` round-trips to the
///    backend on the user-tap path (not just the loser-reconciliation path).
///  - §22 idempotency — every mutating call carries a unique
///    `Idempotency-Key` header generated by the client.
abstract class DriverFlowRepository {
  Future<void> requestOtp(String phoneNumber);

  Future<bool> verifyOtp(String phoneNumber, String otpCode);

  /// Load the authenticated driver's profile (name/TODA/tricycle).
  Future<DriverMeProfile?> myProfile();

  /// Posts current online/offline state with the freshest GPS available.
  ///
  /// PRD §14.1 — when [online] is true, the driver service expects
  /// last-known coordinates; when offline they are ignored server-side.
  Future<bool> updateAvailability(bool online, {double? latitude, double? longitude});

  /// Calls POST /drivers/bookings/{id}/accept with a unique idempotency key.
  Future<DriverOffer> acceptAssignment(DriverOffer offer);

  /// User-initiated decline of an offer (PRD §12).  Distinct from the
  /// loser-reconciliation decline that fires automatically after accept.
  Future<void> declineOffer(DriverOffer offer, {String reasonCode = 'NOT_AVAILABLE'});

  /// Driver-initiated cancel of an already-accepted booking (PRD §11.4).
  Future<DriverBookingCancelResult> cancelBooking(int bookingId, {required String reasonCode, String? notes});

  /// Driver explicitly transitions an accepted booking to DRIVER_ARRIVED.
  Future<void> markArrived({
    required int tripId,
    required double latitude,
    required double longitude,
    double? accuracy,
  });

  /// Driver explicitly transitions an accepted booking to TRIP_IN_PROGRESS.
  Future<void> startTrip({
    required int tripId,
    required double latitude,
    required double longitude,
    double? accuracy,
  });

  /// Driver explicitly transitions an in-progress booking to COMPLETED, then
  /// records the cash payment.  Returns the synthesised summary used by the
  /// End Trip screen.
  Future<DriverTripSummary> endTrip({
    required int tripId,
    required int bookingId,
    required String bookingReference,
    required int passengerCount,
    required double endLatitude,
    required double endLongitude,
    String? fareAmount,
    double? accuracy,
    bool preserveContext = false,
  });

  /// Send a single GPS sample. Used by the in-trip 10s ping and the
  /// online-idle 30s ping.
  Future<void> sendDriverLocation({
    required int tripId,
    required double latitude,
    required double longitude,
    double? accuracy,
  });

  /// Main offer batch, or a single offer when [midAssignment] (from assigned pickup).
  Future<List<DriverOffer>> fetchIncomingOffers({bool midAssignment = false});

  /// Build waiting/onboard lists after the offer batch completes (may use [accepted] data).
  Future<PickupLayout> buildPickupFromAccepted(List<DriverOffer> accepted);

  Future<int> addWalkInPassengers({
    required int existingPassengerCount,
    required int quantity,
    required int capacity,
  });

  /// PRD §16 trip history.  Returns assigned + completed bookings for the
  /// authenticated driver; backend defaults to the latest 50.
  Future<List<DriverHistoryBooking>> myBookings({bool active = false});

  /// PRD §7.19 booking detail (for driver Trip History row tap).
  Future<DriverHistoryBooking?> bookingDetail(int bookingId);

  /// PRD §7.19 — file a dispute (driver role) on a booking.
  ///
  /// [disputeType]: FARE | NO_SHOW | GPS | CONDUCT | SAFETY | OTHER
  Future<void> submitDispute({
    required int bookingId,
    required String disputeType,
    required String description,
  });

  /// True when the implementation can poll backend offers / send GPS pings.
  /// Mocks return false so the controller never starts timers.
  bool get supportsPolling;
}

class DriverBookingCancelResult {
  const DriverBookingCancelResult({required this.bookingId, required this.status, this.cancelledAtIso});

  final int bookingId;
  final String status;
  final String? cancelledAtIso;
}
